const express = require('express')
const router = express.Router()
const userControllers = require('../controllers/user')
router.get('/', userControllers.getAllUser)
router.get('/:id')
router.post('/signup', userControllers.signup)
router.post('/login', userControllers.login)
router.delete('/:userId', userControllers.deleteUser)
router.put('/:userId', userControllers.editUser)
module.exports = router;